services:
  app:
    build:
      context: .
      dockerfile: docker/app/Dockerfile.prod
    container_name: vite-template
    ports:
      - "8080:80"
    environment:
      - NODE_ENV=production
  nginx:
    image: nginx:1.29.2-trixie
    container_name: vite-template-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - prod
